# These are supported funding model platforms

github: articlefr
patreon: articlefr
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: # Replace with a single IssueHunt username
otechie: 
custom: ['https://captchas.io', 'https://www.captchasolutions.com']
